name: xLottery
version: 1.0.0
autor: [xSora, SirHectorin]

main: me.sirhectorin.xlottery.Main
api-version: 1.15

depend: [Vault]

commands:
   lottery:
     description: Lottery
   lot:
     description: Lottery